# -*- coding: utf-8 -*-
"""user_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-870mHldiZ9svkczmIvpy1jMZH4KKxJk
"""

import streamlit as st
import requests

# Backend URL
BACKEND_URL = "https://ai-equity-analyst.onrender.com"

st.set_page_config(page_title="AI Equity Analyst", layout="wide")
st.title("📊 AI Equity Analyst")

# Fetch Available Companies
st.sidebar.header("Select a Company")

try:
    companies_response = requests.get(f"{BACKEND_URL}/companies")
    companies_response.raise_for_status()
    company_list = companies_response.json().get("companies", [])
except requests.exceptions.RequestException:
    company_list = []
    st.sidebar.error("❌ Failed to load companies. Check backend connection.")

if company_list:
    company_name = st.sidebar.selectbox("Choose a Company", company_list)
    if st.sidebar.button("Get Comprehensive Analysis"):
        try:
            response = requests.get(f"{BACKEND_URL}/summary/{company_name}")
            response.raise_for_status()
            analysis = response.json().get("final_summary", "")

            if analysis:
                st.markdown("## AI-Powered Equity Research Report")
                st.write(analysis)
                st.markdown("---")
            else:
                st.warning("⚠️ No analysis available for this company.")
        except requests.exceptions.RequestException:
            st.error("❌ Failed to fetch analysis.")
else:
    st.sidebar.warning("⚠️ No companies available. Try uploading data.")

# 🔹 Disclaimer Section
st.markdown("---")
st.markdown(
    """
    ### ⚠️ Disclaimer:
    This AI-generated content is for informational purposes only and does not constitute financial advice.
    Please consult a qualified financial advisor before making any investment decisions.
    """
)